apiVersion: v1
kind: Deployment
metadata:
  name: mysql
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: db
  template:
    metadata:
      name: mysql
      namespace: roboshop
      labels:
        project: roboshop
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: girishamunnangi/
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec: 
  selector:
    labels:
      project: roboshop
      component: mysql
      tier: db
  ports:
  - Protocol: TCP
    port: 3306
    targetPort: 3306
